### ISSUE TITLE
像这个测试用例，解析不了

### ISSUE THREAD

**Issue by k214k** [netyouli/WHC_DataModelFactory#1]
{

```
    "name":"andy",

    "people":{"name":"andy","age":"28"},

    "friend":["name":"value",

                  {"name":"value","age":"28"}

                 ]

    }
```

**Comment by YiBreeze** [comment]
问题同上

**Comment by netyouli** [comment]
不要黑我好不好，你这是有效json吗，你有校验过吗？？？？？
这是我校验你这json的结果：

Parse error on line 8:
...d": [        "name": "value",        {
----------------------^
Expecting '}', ',', ']'

**Comment by zkfpk6** [comment]
"friend":["name":"value",

                  {"name":"value","age":"28"}

                 ]

这特么什么数组 你在逗我

**Comment by netyouli** [comment]
friend不是数组是什么

**Comment by zkfpk6** [comment]
我说的意思是 数组里怎么能放这玩意"name":"value"，要放也是这么放啊{"name":"value"}

**Comment by netyouli** [comment]
要解析什么是你自己的事情，跟我工具没关系

**Comment by frankfan1990** [comment]
我感觉库作者的理解能力有待提高
