### ISSUE TITLE
2 duplicate symbols for architecture arm64创建第二个Model模型后编译不通过

### ISSUE THREAD

**Issue by ichenwanbing** [netyouli/WHC_DataModelFactory#11]
@netyouli 
duplicate symbol _OBJC_CLASS_$_Data in:
    /Users/chenwanbing/Library/Developer/Xcode/DerivedData/FindingRoof-exfzavygmzrecadxsxznairunkyp/Build/Intermediates/FindingRoof.build/Debug-iphoneos/FindingRoof.build/Objects-normal/arm64/CWBHomeGoodsDetailModel.o
    /Users/chenwanbing/Library/Developer/Xcode/DerivedData/FindingRoof-exfzavygmzrecadxsxznairunkyp/Build/Intermediates/FindingRoof.build/Debug-iphoneos/FindingRoof.build/Objects-normal/arm64/CWBHomeModel.o
duplicate symbol _OBJC_METACLASS_$_Data in:
    /Users/chenwanbing/Library/Developer/Xcode/DerivedData/FindingRoof-exfzavygmzrecadxsxznairunkyp/Build/Intermediates/FindingRoof.build/Debug-iphoneos/FindingRoof.build/Objects-normal/arm64/CWBHomeGoodsDetailModel.o
    /Users/chenwanbing/Library/Developer/Xcode/DerivedData/FindingRoof-exfzavygmzrecadxsxznairunkyp/Build/Intermediates/FindingRoof.build/Debug-iphoneos/FindingRoof.build/Objects-normal/arm64/CWBHomeModel.o
ld: 2 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by netyouli** [comment]
明显有同名的class
