### ISSUE TITLE
期望实现encodeWithCoder 和 initWithCoder 里面的代码

### ISSUE THREAD

**Issue by MelissaShu** [netyouli/WHC_DataModelFactory#13]
期望实现encodeWithCoder 和 initWithCoder 里面的代码

如：

- (void)encodeWithCoder:(NSCoder *)aCoder
{
    [aCoder encodeObject:self.title forKey:@"title"] ;
    [aCoder encodeObject:self.iconName forKey:@"iconName"];
    [aCoder encodeObject:self.iconGrayName forKey:@"iconGrayName"];
    
    [aCoder encodeObject:self.moduleNum forKey:@"moduleNum"];
    [aCoder encodeObject:self.moduleBounceID forKey:@"moduleBounceID"];
    
    [aCoder encodeBool:self.isCanVisit forKey:@"isCanVisit"];
    //    [aCoder encodeObject:self.didClickModuleBlock forKey:@"didClickModuleBlock"];
}

- (instancetype)initWithCoder:(NSCoder *)aDecoder
{
    self = [super init] ;
    if(self)
    {
        self.title = [aDecoder decodeObjectForKey:@"title"] ;
        self.iconName = [aDecoder decodeObjectForKey:@"iconName"];
        self.iconGrayName = [aDecoder decodeObjectForKey:@"iconGrayName"];
        self.moduleNum = [aDecoder decodeObjectForKey:@"moduleNum"] ;
        self.moduleBounceID = [aDecoder decodeObjectForKey:@"moduleBounceID"] ;
        self.isCanVisit = [aDecoder decodeBoolForKey:@"isCanVisit"] ;
        
    }
    return self ;
}

**Comment by netyouli** [comment]
现在主流json开源库都有api自动对模型进行kvc，并且由于复杂json如果这样一行一行推起来，模型文件估计很难看所以还是用第三方json库里的api吧，本人的json解析[WHC_Model](https://github.com/netyouli/WHC_Model)，[SexyJson](https://github.com/netyouli/SexyJson)，有兴趣可以去了解一下

**Comment by KateSS** [comment]
好的，谢谢
