### ISSUE TITLE
未知数据格式无法解析(请提供json字符串或者dictionary字符串)

### ISSUE THREAD

**Issue by qinjianwei** [netyouli/WHC_DataModelFactory#15]
转换的时候提示『未知数据格式无法解析(请提供json字符串或者dictionary字符串)』
<img width="1024" alt="2017-05-27 7 25 08" src="https://cloud.githubusercontent.com/assets/17981557/26515486/bedf5c68-42ad-11e7-8507-05c141357bf2.png">

**Comment by netyouli** [comment]
这json格式有问题，你可以去找个json格式校验工具验证一下
