### ISSUE TITLE
json 转模型的时候 首字母变成大写

### ISSUE THREAD

**Issue by QingMu1** [netyouli/WHC_DataModelFactory#20]
原json --------
{
  "Citys" : [
    {
      "Code" : "140100",
      "Name" : "太原市"
    },
    {
      "Code" : "140200",
      "Name" : "大同市"
    },
    {
      "Code" : "140400",
      "Name" : "长治市"
    },
    {
      "Code" : "140500",
      "Name" : "晋城市"
    }
  ],
  "Code" : "140000",
  "Name" : "山西省"
}

model ----------
@interface Citys :NSObject
@property (nonatomic, copy) NSString              * code;
@property (nonatomic, copy) NSString              * name;

@end

@interface WHC :NSObject
@property (nonatomic, strong) NSArray<Citys *>              * citys;
@property (nonatomic, copy) NSString              * code;
@property (nonatomic, copy) NSString              * name;

@end

请问这个怎么关闭

**Comment by netyouli** [comment]
类名默认首字母大写，属性名首字母默认小写，如果不需要默认处理把handle first勾选去掉即可
