### ISSUE TITLE
无法打出英文格式的引号 

### ISSUE THREAD

**Issue by CoderAndCat** [netyouli/WHC_DataModelFactory#21]
<img width="402" alt="2017-12-05 09 20 09" src="https://user-images.githubusercontent.com/22518690/33585125-a6e96004-d99d-11e7-9f7f-a1a910d6a878.png">

图中的无法识别，是我输入的有问题吗？

**Comment by netyouli** [comment]
看错误提示。要输入正确格式的json字符串
