### ISSUE TITLE
建议添加字典本身解析、添加一键清空

### ISSUE THREAD

**Issue by lincoly** [netyouli/WHC_DataModelFactory#4]
像字典直接打印出来的无法解析：如` {
    responseCode = 1;
    responseData =     {
        commissionLogInfo =         (
                        {
                affectMoney = "6666666.66";
                createTime = 1478607300753;
                page = 1;
                rows = 10;
                userName = "\U5468**";
            }
        );
    };
    responseMsg = "";
}`

解决方法为：在json转字典时，添加`if (!dict) {
                dict = json.propertyListFromStringsFileFormat;
            }`

一键清空非常有必要

**Comment by netyouli** [comment]
恩不错建议，感谢！

**Comment by netyouli** [comment]
不过这个有问题，转了之后都是String类型这肯定是不对的

**Comment by netyouli** [comment]
一键清空已经有，你只需要重新make就行了

**Comment by lincoly** [comment]
`if(json && json.length){
        NSDictionary  * dict = nil;
        if([json hasPrefix:@"<"]){
            //xml
            dict = [WHC_XMLParser dictionaryForXMLString:json];
        }else{
            //尝试json转字典
            NSData  *jsonData = [json dataUsingEncoding:NSUTF8StringEncoding];
            dict = [NSJSONSerialization JSONObjectWithData:jsonData options:NSJSONReadingMutableLeaves error:NULL];
            //json转失败，尝试直接取属性列表为字典
            if (!dict) {
                dict = json.propertyListFromStringsFileFormat;
            }
            
        }`

**Comment by netyouli** [comment]
我知道，dict = json.propertyListFromStringsFileFormat;这个转换出来dict是有问题的除了字典和数组对应值是对的其他key对应的value类型都不对都是String类型，而实际开发中有的是Int，Float，Bool类型，如果你直接用这样的模型类肯定会出错的，不过也已经支持这样的字符串，但是非常不建议用NSDictionary，可以说这本身就是个错误

**Comment by lincoly** [comment]
int 转为String类型也是可以的，只不过取值取intValue而已，这只是妥协的办法，多一种支持格式。我个人习惯是直接打印字典，而不是转json再打印，支持这种格式只是我的需求哈。

**Comment by netyouli** [comment]
你模型都是声明类型和实际用时类型不一致，叫别人以后如何去维护，做开发还是要基本责任感，不能为了自己的方便和习惯给别人造成困扰，这种方式只适合模型类是纯字符串类型的时候使用，主要还是以json/xml字符串为主
