### ISSUE TITLE
WHC_DataModelFactory一些补充

### ISSUE THREAD

**Issue by DolphinsLoveCats** [netyouli/WHC_DataModelFactory#8]
我大概使用了一下这个app 觉得甚是好用,不过在使用期间还是发现了一些小问题
比如:对于后台直接返回id,copy 等关键字 解析的时候希望直接转为大写,这样在项目内使用不会出现问题,同时可以加以注释说明,这个被自动转为大写了,达到更好的 自动化.
 期待您的新版本.

**Comment by netyouli** [comment]
这个是这样的，很多第三方库都支持model类起别名的比如WHC_Model，像json里面有你说的id，copy这样的字段，你可以手动改为其他名称，然后用第三方model库比如WHC_Model给映射一下就行了

**Comment by netyouli** [comment]
刚刚更新了v1.8.3版本修复了UI显示问题
