### ISSUE TITLE
内容复制进去一片黑

### ISSUE THREAD

**Issue by StarYellow** [netyouli/WHC_DataModelFactory#9]
![qq20161229-0](https://cloud.githubusercontent.com/assets/13357868/21536091/09158b14-cdb9-11e6-8431-5a834bf5d421.png)

**Comment by netyouli** [comment]
已更新了，最新版本是v1.8.3了

**Comment by StarYellow** [comment]
我试一下一下 还是一样。。 从xcode的console复制的话 会复制富文本 会复制jsonstring的颜色 导致复制进去的变成黑色字体了

**Comment by netyouli** [comment]
直接点击转换按钮就好了
